/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleType } from "./role-type";

 /**
 * 
 *
 * @export
 * @interface AdminUserUpdateRequestDto
 */
export interface AdminUserUpdateRequestDto {

    /**
     * @type {string}
     * @memberof AdminUserUpdateRequestDto
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof AdminUserUpdateRequestDto
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof AdminUserUpdateRequestDto
     */
    email: string;

    /**
     * @type {RoleType}
     * @memberof AdminUserUpdateRequestDto
     */
    userRole: RoleType;
}
