/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CategoryRequestDto
 */
export interface CategoryRequestDto {

    /**
     * @type {string}
     * @memberof CategoryRequestDto
     */
    categoryName: string;

    /**
     * @type {string}
     * @memberof CategoryRequestDto
     */
    parentCategoryId?: string | null;
}
