/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CartItemRequestDto } from './cart-item-request-dto';
import { PaymentMethod } from './payment-method';
import { ShippingMethod } from './shipping-method';
 /**
 * 
 *
 * @export
 * @interface OrderCreateRequestDto
 */
export interface OrderCreateRequestDto {

    /**
     * @type {string}
     * @memberof OrderCreateRequestDto
     */
    customerId: string;

    /**
     * @type {number}
     * @memberof OrderCreateRequestDto
     */
    totalQuantity: number;

    /**
     * @type {number}
     * @memberof OrderCreateRequestDto
     */
    totalAmount: number;

    /**
     * @type {ShippingMethod}
     * @memberof OrderCreateRequestDto
     */
    orderShippingMethod: ShippingMethod;

    /**
     * @type {PaymentMethod}
     * @memberof OrderCreateRequestDto
     */
    orderPaymentMethod: PaymentMethod;

    /**
     * @type {Array<CartItemRequestDto>}
     * @memberof OrderCreateRequestDto
     */
    cartItems: Array<CartItemRequestDto>;
}
