/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReviewCreateRequestDto
 */
export interface ReviewCreateRequestDto {

    /**
     * @type {string}
     * @memberof ReviewCreateRequestDto
     */
    productId: string;

    /**
     * @type {string}
     * @memberof ReviewCreateRequestDto
     */
    reviewText: string;

    /**
     * @type {number}
     * @memberof ReviewCreateRequestDto
     */
    rating: number;
}
