/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface WeatherForecast
 */
export interface WeatherForecast {

    /**
     * @type {string}
     * @memberof WeatherForecast
     */
    date?: string;

    /**
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureC?: number;

    /**
     * @type {number}
     * @memberof WeatherForecast
     */
    temperatureF?: number;

    /**
     * @type {string}
     * @memberof WeatherForecast
     */
    summary?: string | null;
}
