version: '3.4'

services:
  app:
    image: cosmeticshop-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Port=3306;Database=cosmetics_store_db;User=root;Password=AnnaOnisSQL_84;
    ports:
      - "5000:8080"
      - "5050:8081"
    volumes:
      - ./Presentation/cosmeticshop.client:/app/wwwroot
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https

