/* tslint:disable */
/* eslint-disable */
/**
 * CosmeticShop.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/auth-api';
export * from './apis/cart-api';
export * from './apis/category-api';
export * from './apis/customer-api';
export * from './apis/order-api';
export * from './apis/products-api';
export * from './apis/reviews-api';
export * from './apis/user-api';
export * from './apis/weather-forecast-api';

